### ISSUE TITLE
export command execution

### ISSUE THREAD

**Issue by zjamali** [zjamali/minishell-42cursus#40]
export 1TEST= ; env | sort | grep -v SHLVL | grep -v _=
export ""="" ; env | sort | grep -v SHLVL | grep -v _=
export TEST=LOL ; echo $TEST ; env | sort | grep -v SHLVL | grep -v _=
export TEST=LOL; export TEST+=LOL ; echo $TEST ; env | sort | grep -v SHLVL | grep -v _=
export TEST="ls -l - a" ; echo $TEST ; $LS ; env | sort | grep -v SHLVL | grep -v _=

"echo    $TEST lol $TEST"

mkdir test_dir ; cd test_dir ; rm -rf ../test_dir ; cd . ; pwd ; cd . ; pwd ; cd .. ; pwd

**Comment by barimehdi77** [comment]
sat f `"echo $TEST lol $TEST"` rah kayn moshkil f parsing hitash katpassili f `cmd= echo lol`
![Screenshot 2021-05-01 23:29:11](https://user-images.githubusercontent.com/54292953/116801157-13179280-aad5-11eb-9a94-1a69686c285a.png)

**Comment by barimehdi77** [comment]
sat had lblan hta hwa rah b7al li 9bl nta katpassili `ls -l -a` kamla f cmd mshi `ls` f cmd o `-l -a` f args
<img width="450" alt="Screen Shot 2021-05-02 at 4 28 14 PM" src="https://user-images.githubusercontent.com/54292953/116820227-69331700-ab63-11eb-9fb5-9d7512f415c5.png">

**Comment by barimehdi77** [comment]
about this : `mkdir test_dir ; cd test_dir ; rm -rf ../test_dir ; cd . ; pwd ; cd . ; pwd ; cd .. ; pwd`

hada asat rah wa9ila hta shi wa7d mn ecole ma daro o asalan ma3rft hta kifash ghadi nhandlih

**Comment by zjamali** [comment]
env variable used like cmd fixed:
<img width="601" alt="Screen Shot 2021-05-03 at 5 17 41 PM" src="https://user-images.githubusercontent.com/57237871/116909323-96e79100-ac33-11eb-868c-8ec0ad840f94.png">

**Comment by barimehdi77** [comment]
done
