### ISSUE TITLE
the exit status of syntax error

### ISSUE THREAD

**Issue by barimehdi77** [zjamali/minishell-42cursus#41]
command : `;;`
error : `minishell: syntax error near unexpected token ';;'`
the returned status code in **minishell**: `0`
the returned status code in **bash**: `258`
screenshot from **minishell**:
<img width="441" alt="Screen Shot 2021-04-30 at 4 31 01 PM" src="https://user-images.githubusercontent.com/54292953/116725708-d7e06b00-a9d1-11eb-81a2-2d879150041c.png">
screenshot from **bash**:
<img width="403" alt="Screen Shot 2021-04-30 at 4 31 19 PM" src="https://user-images.githubusercontent.com/54292953/116725714-d9119800-a9d1-11eb-99df-6cc18265f3d9.png">

**Comment by zjamali** [comment]
fixed
