### ISSUE TITLE
echo problems and exit segfault

### ISSUE THREAD

**Issue by zjamali** [zjamali/minishell-42cursus#44]
![Screen Shot 2021-05-01 at 04 11 41](https://user-images.githubusercontent.com/57237871/116770432-794bd900-aa33-11eb-90b7-156d53a931fc.png)
-----------------------
![Screen Shot 2021-05-01 at 04 12 15](https://user-images.githubusercontent.com/57237871/116770428-7355f800-aa33-11eb-8124-03725b216d0e.png)
! kat stopi printing mni katl9a lowla empty string walkin li wraha machi empty string
![Screen Shot 2021-05-01 at 04 13 11](https://user-images.githubusercontent.com/57237871/116770438-95e81100-aa33-11eb-980a-7c15de56c54d.png)
-----------------------
![Screen Shot 2021-05-01 at 04 25 18](https://user-images.githubusercontent.com/57237871/116770727-4571b300-aa35-11eb-9d17-e31c82dcfca1.png)

**Comment by barimehdi77** [comment]
sf asat 3awd jrb db rah fixitha
